/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtualizarRouteImport } from './routes/atualizar'
import { Route as CanhotosRouteImport } from './routes/canhotos'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as ProdutividadeRouteImport } from './routes/produtividade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizarRoute = AtualizarRouteImport.update({
  id: '/atualizar',
  path: '/atualizar',
  getParentRoute: () => rootRouteImport,
} as any)
const CanhotosRoute = CanhotosRouteImport.update({
  id: '/canhotos',
  path: '/canhotos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutividadeRoute = ProdutividadeRouteImport.update({
  id: '/produtividade',
  path: '/produtividade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atualizar': typeof AtualizarRoute
  '/canhotos': typeof CanhotosRoute
  '/historico': typeof HistoricoRoute
  '/horarios': typeof HorariosRoute
  '/pendencias': typeof PendenciasRoute
  '/produtividade': typeof ProdutividadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atualizar': typeof AtualizarRoute
  '/canhotos': typeof CanhotosRoute
  '/historico': typeof HistoricoRoute
  '/horarios': typeof HorariosRoute
  '/pendencias': typeof PendenciasRoute
  '/produtividade': typeof ProdutividadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atualizar': typeof AtualizarRoute
  '/canhotos': typeof CanhotosRoute
  '/historico': typeof HistoricoRoute
  '/horarios': typeof HorariosRoute
  '/pendencias': typeof PendenciasRoute
  '/produtividade': typeof ProdutividadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atualizar'
    | '/canhotos'
    | '/historico'
    | '/horarios'
    | '/pendencias'
    | '/produtividade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atualizar'
    | '/canhotos'
    | '/historico'
    | '/horarios'
    | '/pendencias'
    | '/produtividade'
  id:
    | '__root__'
    | '/'
    | '/atualizar'
    | '/canhotos'
    | '/historico'
    | '/horarios'
    | '/pendencias'
    | '/produtividade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtualizarRoute: typeof AtualizarRoute
  CanhotosRoute: typeof CanhotosRoute
  HistoricoRoute: typeof HistoricoRoute
  HorariosRoute: typeof HorariosRoute
  PendenciasRoute: typeof PendenciasRoute
  ProdutividadeRoute: typeof ProdutividadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizar': {
      id: '/atualizar'
      path: '/atualizar'
      fullPath: '/atualizar'
      preLoaderRoute: typeof AtualizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canhotos': {
      id: '/canhotos'
      path: '/canhotos'
      fullPath: '/canhotos'
      preLoaderRoute: typeof CanhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtividade': {
      id: '/produtividade'
      path: '/produtividade'
      fullPath: '/produtividade'
      preLoaderRoute: typeof ProdutividadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtualizarRoute: AtualizarRoute,
  CanhotosRoute: CanhotosRoute,
  HistoricoRoute: HistoricoRoute,
  HorariosRoute: HorariosRoute,
  PendenciasRoute: PendenciasRoute,
  ProdutividadeRoute: ProdutividadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
